Feature ast compiler
jeff5/very-slow-jython pull request #3
Opened 2024-05-14 03:43 UTC by fwierzbicki

I'm not sure why this PR is showing upstream commits (I guess because I had to merge them?)

My only changes are:

	modified:   rt3.gradle
	deleted:    src/main/java/uk/co/farowl/vsj3/evo1/parser/TokenType.java
	new file:   src/main/token/Tokens
	new file:   tools/python/lib/generate_token.py
	new file:   tools/python/lib/generate_token_java.py

2024-05-14 07:59 UTC, jeff5 commented
> I'm not sure why this PR is showing upstream commits (I guess because I had to merge them?)

Yes, I think because these changes arrived on the `main` branch after after the feature branch started, and you merged them, now your PR is adding them to the branch. I think they might go away, in the "files changed", anyway, if I merge `main` myself into the feature branch. (Theory: a PR is a kind of diff with the current state.)

2024-05-14 09:25 UTC, jeff5 requested changes
I have more thoughts, but I'll end up writing them all twice (once here, once in Pegen2). So hang fire here and I'll pull Pegen2 and have a look.

2024-05-14 09:25 UTC, jeff5 commented on rt3/tools/python/lib/generate_token.py
> +# from tag v3.11.9
Given that we're editing this I would add ... "so that we can use its methods from generate_token_java.py."

I like that `Tokens` is exactly as in CPython (so one can just copy an updated one), so it's a pity this isn't. But we ought to leave an audit trail of some kind ... maybe there's a non-intrusive way if we explain it all in `generate_token_java.py`?

2024-05-14 09:25 UTC, jeff5 commented on rt3/tools/python/lib/generate_token_java.py
> +    write("switch (c%d) {\n" % (level,))
f-strings are nicer (here and everywhere). I realise this is following a CPython original using old-school %-formatting.

Also, where I'm already generating Java with Python, I have a library that might be useful. The best thing in it is a context manager that does the indenting for you. See: https://github.com/jeff5/very-slow-jython/blob/a11055110c1397a3141a46fd199eef593535a67b/rt3/tools/python/lib/evo1/PyLong.py#L519-L526 using support from https://github.com/jeff5/very-slow-jython/blob/main/rt3/tools/python/lib/srcgen.py.

Tobias didn't choose to use that in Pegen2, but we can in Jython.

2024-05-14 09:25 UTC, jeff5 commented on rt3/tools/python/lib/generate_token_java.py
> +package uk.co.farowl.vsj3.evo1.parser;
Prefer to make this an argument: one less thing to remember when porting to Jython 3.

2024-06-01 17:01 UTC, jeff5 commented
> I'm not sure why this PR is showing upstream commits (I guess because I had to merge them?)

We've reviewed (and improved a bit) these changes on Pegen2, and have an idea where to go on that project, so I think this PR is stale.

Also, it targets what was only ever an experimental branch looking at how Pegen might integrate. Parts of it (in the compiler, not the tokenizer, which is good) aren't what I think we want, so I'm unlikely to merge that branch into the main VSJ project.

2024-06-02 18:34 UTC, fwierzbicki commented
Works for me, closing this

2024-06-02 18:34 UTC, closed without merging